### PR TITLE
add filter and sparse-checkout opitons

### LINKED ISSUE #7: Custom working directory
Hi. Is there a way to set a custom working directory when using this workflow?

[This SO answer](https://stackoverflow.com/questions/58139175/running-actions-in-another-directory/63122434#63122434) points out a way, but it does not work well with the workflow, because the directory does not exist before workflow run.

### PR DESCRIPTION
**Pull request by mickmcgrath13**
fixes https://github.com/bitovi/github-actions-react-to-github-pages/issues/7

### CODE REVIEW

**Review by mcascone — CHANGES_REQUESTED** [review]
LGTM pending answer if `CONE` should be `CLONE`

**Review by LeoDiazL — APPROVED** [review]
LGTM

**Review by mcascone — CHANGES_REQUESTED** [review]
@LeoDiazL I still don't see a resolution on `cone` vs. `clone`. What is the correct term?

**Comment by mickmcgrath13** [comment]
@mcascone it's an option here: https://github.com/actions/checkout

also: https://git-scm.com/docs/sparse-checkout#_terminology

> cone mode: one of two modes for specifying the desired subset of files in a sparse-checkout. In cone-mode, the user specifies directories (getting both everything under that directory as well as everything in leading directories), while in non-cone mode, the user specifies gitignore-style patterns. Controlled by the --[no-]cone option to sparse-checkout init|set.

**Pull request merged**
